### ISSUE TITLE
Datation des affaires

### ISSUE THREAD

**Issue by emchateau** [anrExperts/data#41]
Les affaires peuvent s’étaler sur plusieurs années (parfois jusqu’à 10 ans). Le début des ensemble de cotes dépouillés contiennent parfois également des affaires débutées l’année précédente. Par ailleurs, toutes les dates n’ont pas été relevées pour les affaires comprenant un nombre de vacations importantes.
- Quelle année retenir pour classer les affaires ?
- Comment identifier les affaires dont le détail des vacations n’a pas été relevé ?

voir également l‘#120

**Comment by emchateau** [comment]
**Sur l’identification des affaires** dont le détail des vacations n’a pas été relevé, si le prix a été relevé, on devrait pouvoir les relever. Il s’agit aussi souvent d’affaires concernant la province. Il convient d’explorer les commentaires.

**Comment by sardinecan** [comment]
J'ai ajouté un « champ » date dans le sourceDesc correspondant à l'année du carton pour toutes les affaires. Toutes les affaires sont donc maintenant datées au regard de leur carton.
